---
services:
  healthchecks:
    environment:
      ALLOWED_HOSTS:
      APPRISE_ENABLED:
      DEBUG:
      DEFAULT_FROM_EMAIL:
      EMAIL_HOST:
      EMAIL_HOST_PASSWORD:
      EMAIL_HOST_USER:
      EMAIL_PORT:
      EMAIL_USE_TLS:
      INTEGRATIONS_ALLOW_PRIVATE_IPS:
      PGID:
      PING_EMAIL_DOMAIN:
      PUID:
      REGENERATE_SETTINGS:
      SECRET_KEY:
      SITE_LOGO_URL:
      SITE_NAME:
      SITE_ROOT:
      SUPERUSER_EMAIL:
      SUPERUSER_PASSWORD:
      TZ:
    image: linuxserver/healthchecks:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
